In [1]:
import pandas as pd 
import matplotlib.pyplot as plt

In [2]:
df1 = pd.read_csv('tennis_courtsV1.csv')
df1.head()

,Unnamed: 0,name,address,city,zip_code,type,count,clay,wall,grass,indoor,lights,proshop,latitude,clay.1,wall.1,grass.1,indoor.1,lights.1,stringing
0,Northwestern High,Adelphi Road,washington,dc,Public,6,False,True,False,False,False,False,38,-76.952112,0,1,0,0,0,0
1,The Park at Canterbury,Brandywood Circle,orlando,fl,Homeowners Community,1,False,False,False,False,True,False,28,-81.285224,0,0,0,0,1,0
2,Tippit Middle School,Greenlee Drive,austin-san marcos,tx,Public,8,False,True,False,False,True,False,30,-97.700794,0,1,0,0,1,0
3,Lexington Park,McKee Street,minneapolis-st. paul,mn,Public,1,False,False,False,False,False,False,44,-93.142100,0,0,0,0,0,0
4,Rogers Junior School,Avenue North,minneapolis-st. paul,mn,Public,6,False,False,False,False,False,False,45,-93.544174,0,0,0,0,0,0

In [3]:
df1.drop(columns=['clay', 'wall', 'grass', 'indoor', 'lights'], inplace=True)
df1.rename(columns={'clay.1': 'clay', 'wall.1': 'wall', 'grass.1': 'grass', 'indoor.1': 'indoor', 'lights.1': 'lights'}, inplace=True)
df1.head()

,Unnamed: 0,name,address,city,zip_code,type,count,proshop,latitude,clay,wall,grass,indoor,lights,stringing
0,Northwestern High,Adelphi Road,washington,dc,Public,6,False,38,-76.952112,0,1,0,0,0,0
1,The Park at Canterbury,Brandywood Circle,orlando,fl,Homeowners Community,1,False,28,-81.285224,0,0,0,0,1,0
2,Tippit Middle School,Greenlee Drive,austin-san marcos,tx,Public,8,False,30,-97.700794,0,1,0,0,1,0
3,Lexington Park,McKee Street,minneapolis-st. paul,mn,Public,1,False,44,-93.142100,0,0,0,0,0,0
4,Rogers Junior School,Avenue North,minneapolis-st. paul,mn,Public,6,False,45,-93.544174,0,0,0,0,0,0